### ISSUE TITLE
Will not Copy Whole Block

### ISSUE THREAD

**Issue by lanameredice** [LadyDefile/Wordsmith-DalamudPlugin#14]
Sometimes, very rarely, on posts that have more than one block, the scratch pad will not copy the entire block. It will only copy until the end of the next sentence and fail to copy the rest. It may be trying to put another break in, but doesn't.

**Comment by LadyDefile** [comment]
The next time this happens, please paste the broken text here along with a screenshot of the scratchpad and send it.

**Comment by lanameredice** [comment]
Hi there!

It happened again. Here is the broken text and a screenshot of the scratchpad:

handed him the half-eaten bucket, now ice-cream soup, and laughed

.

"Jörgen just wants to see what all the fuss is about. And, apparently, is

looking for more chocobo meat from you, since you keep /feeding him

the feathers./ It's your own fault." She sniffed and tossed her head,

sticking her nose up in the air, but unable to keep the smile off of her

lips. She gave him one last, tight hug. "Thank you, Cer. For being you."

She groaned as she stood and stretched. "Right now, I have a date with

the bath room. I'll see you around for training.
![Capture1](https://user-images.githubusercontent.com/88600784/173171936-87b8a0b1-42e9-4bf3-b4b0-3079d95d5012.PNG)
![Capture](https://user-images.githubusercontent.com/88600784/173171937-4832f2f0-0c90-448c-8c80-f112b37150bd.PNG)
"

**Comment by LadyDefile** [comment]
Interesting. That period is wrapped to it's own line in the text you pasted. I'll have to dig around to see if I can replicate the issue.

**Comment by lanameredice** [comment]
It may have to deal with me going back and edited my posts as I type them. On this one, I removed a few words from the end of that sentence. However, when I realized what had happened, I tried to remove the period and shift and adjust, however it kept assigning it it's own line.

**Comment by LadyDefile** [comment]
Ok. I have a suspicion. Next time it happens, try this. Delete the period and the letter in front of it. Because Dalamud's UI doesn't support wrapped text boxes I had to encode my own with a custom wrapping system. Unfortunately, the only way to do that was by using newline and return carriage characters as markers. What is likely happening is the edit manages to get between these tags and break the wrapping system. I have code in place to minimize this possibility,  but I can only do so much without rewriting the entire text system.

For reference:
handed him the half-eaten bucket, now ice-cream soup, and laughed

.

Actually looks like this to the plugin:
handed him the half-eaten bucket, now ice-cream soup, and laughed/r/r./n

**Comment by lanameredice** [comment]
I'll definitely give it a go and see if that fixes it. I'll let you know if/when it happens again.

**Comment by LadyDefile** [comment]
Wordsmith uses /n to mark a user hitting enter, /r/n to mark a split, and /r/r/n to mark a split that replaced a space.
