### ISSUE TITLE
Dictionary not working

### ISSUE THREAD

**Issue by RueD123** [LadyDefile/Wordsmith-DalamudPlugin#44]
Updated recently after new patch
Dictionary is not working unless you go into settings , reload dictionary, then apply
Only one scratch pad in use

**Comment by smskhyron** [comment]
Since FF14 6.5 the spell check doesn't highlight misspelled words. Using the tips above doesn't fix it for me. I'm a horrible speller, hoping you can fix it. :)  Ty

**Comment by LadyDefile** [comment]
I've been rather busy and haven't had the opportunity to look into the issue but I should be able to check in on it in the next day or two and figure out why it's not functioning properly.

**Comment by smskhyron** [comment]
Totally understand, and of course no rush. appreciate you looking when you get time.

**Comment by LadyDefile** [comment]
I can't seem to replicate the issue yet. I'll keep playing with it though. If you check your logs, do you see any errors from Wordsmith?

**Comment by smskhyron** [comment]
Sorry, I'm not to savvy with all this, i didn't see a log under the wordsmith folder, nor a button for logs when in the plugin itself. I can look at the logs if you dont mind pointing me to where I could look for them.
I did just uninstall and reinstall it, reset it to default, and deleted my custom dictionary. I still have the issue where misspelled words dont show like it used to.
Thanks!

**Comment by LadyDefile** [comment]
> Sorry, I'm not to savvy with all this, i didn't see a log under the wordsmith folder, nor a button for logs when in the plugin itself. I can look at the logs if you dont mind pointing me to where I could look for them. I did just uninstall and reinstall it, reset it to default, and deleted my custom dictionary. I still have the issue where misspelled words dont show like it used to. Thanks!

Absolutely! So Dalamud has a built-in logging system. Just type /xllogs and the log console should appear.

**Comment by smskhyron** [comment]
thanks! unfortunately, the logs dont show any errors for wordsmith, just that it loaded. I search for the word "word" and "dictionary" and "spell" and nothing.
If there is something else i should search for, please let me know. thanks again!

**Comment by LadyDefile** [comment]
You should be able to scroll through and look for any lines that are colored red. Any text in red is an error message.
Also, just to be sure, you are able to view this link, yes? https://github.com/LadyDefile/WordsmithDictionaries/blob/main/library/lang_en

In the mean time you can also try using local dictionary. To use local dictionary you need to follow the steps below:
* Create the `Dictionaries` directory in `%appdata%/XIVLauncher/installedPlugins/Wordsmith`
* Download the lang_en file linked above and save it with no file extension. (lang_en not lang_en.txt)
* Place the lang_en file into your `%appdata%/XIVLauncher/installedPlugins/Wordsmith/Dictionaries` directory.
* Restart Wordsmith.
* Open Wordsmith Settings.
* Navigate to the `Spell Check` tab.
* Select the `Dictionary Selection` drop down box and choose the `local: lang_en` option.
* Click `Reload Dictionary`

Note that if you use a local dictionary file, any future updates may delete this file and require you to follow the above steps again or require you place them in a different folder.

I initially moved to this web-based dictionary because it's over 30MB on its own which doesn't seem like much but in the context of a Dalamud Plugin, it was massive (Most plugins are just 1-3MB). It was actually so big that it caused the Dalamud building system (which validates packages and ensures no malicious code gets through) to actually crash when I attempted to add a second language.

**Comment by dectala** [comment]
I have had similar issues and the above directions didn't seem to work, or more it's not detected on the list of dictionaries even after restarting my game. The Dictionaries directory did not even exist till I created it.

I did however notice some things, with the web dictionary still that may help hopefully? If I disable "Auto Spell check" and hit apply it still seems to auto spell check. Though if I do keep this disabled manually triggering the spell check seems to work just fine for me. I also can replicate triggering the spell check anytime I hit apply. I don't have to reload a dictionary. Just apply on settings and it'll spell check. I'm not sure if this helps but don't hesitate to ask me for more. I'm happy to provide what i can.

**Comment by dectala** [comment]
I'm not sure how I add stuff I use GitLab more than GitHub and it seems to be a bit different. So I'm sorry if there should be a proper place to add. But it also seems it's only checking the first word.

If I do something like wnats this teh and manually spell check. It only checks wnats. If I ignore it and just hit enter it won't check teh. If I spell check a 2nd time, use the spell check to correct wnats to want it won't trigger on teh. But if I run a spell check a third time, it will then noticed teh.

**Comment by LadyDefile** [comment]
> I'm not sure how I add stuff I use GitLab more than GitHub and it seems to be a bit different. So I'm sorry if there should be a proper place to add. But it also seems it's only checking the first word.
> 
> If I do something like wnats this teh and manually spell check. It only checks wnats. If I ignore it and just hit enter it won't check teh. If I spell check a 2nd time, use the spell check to correct wnats to want it won't trigger on teh. But if I run a spell check a third time, it will then noticed teh.

That is very strange behavior. I'll look into this a bit more. Thanks for letting me know.

**Comment by smskhyron** [comment]
The steps for a local dictionary didn't work for me, but I tried the trick Lurasa mentioned, turning off autospell, and it will then check one misspelled for me too

Didn't see any relevant errors in the logs

I also noticed that if I just go to the "text" menu then "spellcheck" to manually tell it to check, it will then highlight the first misspelled word as well. 

And maybe im remembering it wrong, but i thought it would give spelling suggestions sometimes when you right click if it has ideas on what you might be trying to spell? that might just be me remembering wrong though lol

Anyway, hope the above info helps. and thank you

**Comment by LadyDefile** [comment]
Yes, you should be able to get word suggestions like this:
![image](https://github.com/LadyDefile/Wordsmith-DalamudPlugin/assets/67084868/ccb63577-eb73-4a7c-afac-54224a46dc5f)

If you could send me your Wordsmith config file, maybe I can figure out what the cause is there.

**Comment by LadyDefile** [comment]
I believe I have identified a build flaw in the Wordsmith system that should fix some big problems. The problem was wrapped in a build flag preprocessor statement which is a fancy way of saying "It only worked right when I was testing it". Update should be out shortly. If you still have issues, please open another ticket.
