### ISSUE TITLE
Unable to Resize Windows

### ISSUE THREAD

**Issue by bhaalian** [LadyDefile/Wordsmith-DalamudPlugin#46]
Hi there. Ever since I had to factory-reset my computer (and completely reinstall FFXIV/Dalamud), my Wordsmith windows ("Settings" and "Scratchpad") have been displaying at a weird resolution. They will not let me resize them past a certain point, which is still way too big (pictured below).
![wordsmith 1](https://github.com/LadyDefile/Wordsmith-DalamudPlugin/assets/149650078/81994c00-856a-4fe0-9a49-25ba57ad94d5)
![wordsmith 2](https://github.com/LadyDefile/Wordsmith-DalamudPlugin/assets/149650078/7ccfb58b-ca2b-4545-acc3-b869e19c92cd)
The windows' displays don't seem to be displaying correctly either. For example, the lock icon on my Scratchpad is cut off by the chat header dropdown, which you can see above. Not pictured are the buttons at the bottom right of the "Settings" window, which appear without any text on them whatsoever.

I've also attached my game's resolution settings just in case.
![Screenshot 2023-11-02 012026](https://github.com/LadyDefile/Wordsmith-DalamudPlugin/assets/149650078/7e0966b8-2f0f-4760-bd90-711b0b58c3e9)

**Comment by LadyDefile** [comment]
Thank you for pointing this out! I don't have a 4k screen so it's very difficult for me to test out high resolutions like this. I believe I found the issue.

The lock button wasn't being scaled because I hadn't enabled scaling on the container that holds the button.
The form size issue is sort of the opposite. It automatically scales the minimum form size and I was also scaling the form size. So the minimum width of 375 became 1,125, became 3375... Taking up nearly your entire monitor. The good news is, I found the issue and have already fixed it. This will be available in the next update!

**Comment by bhaalian** [comment]
Thank you so much!! I adore your plugin btw!!

**Comment by LadyDefile** [comment]
I'm glad you like it so much! It has been quite a big project to get it to where it is now, lol. The update should be out so as soon as you update it, hopefully it's fixed for you!

**Comment by bhaalian** [comment]
I just checked, and it's fixed! Thank you again!!
